### ISSUE TITLE
Metrics for consented requests

### ISSUE THREAD

**Issue by maciejkowalczyk** [privacysandbox/bidding-auction-servers#39]
Hi,
We've noticed that each consented request causes creating a set of metrics with a unique `generation_id` attribute value.
These metrics accumulate over time until service instance of restarted.

It's possible to filter them in collector service but default otlp collector setup doesn't do it.
This causes unnecessary metrics ingest costs and suggests there is a resource leak in services code

**Comment by xinggao01** [comment]
Hi Maciej,

We added `generation_id` to provide metrics per request to help debugging in production. Since the number of consented requests in practice should be low, its impact on production costs should be minimal. Why do you see high volume of consented requests?

To remove it, you can add attributes processor to remove the `generation_id` in otel collector config.

```
processors:
  attributes/rm_gen_id:
    actions:
      - key: generation_id
        action: delete
        
service:
  pipelines:
    metrics:
      processors: [batch, attributes/rm_gen_id]  
```

**Comment by fhoering** [comment]
It looks like an easy way to kill ad tech traffic as you can just inject a bunch of consented traffic requests with new guids until the servers go down.

On our side we also noticed that there are many metrics with many dimensions that are created and it generates a significant cost already.

**Comment by fhoering** [comment]
> To remove it, you can add attributes processor to remove the generation_id in otel collector config.

It looks like this is possible in [GCP ](https://github.com/privacysandbox/bidding-auction-servers/blob/68c22a0c61d8320b655328dcfe0b28c59fd69475/production/deploy/gcp/terraform/services/autoscaling/collector_startup.tftpl) but not in [AWS](https://github.com/privacysandbox/bidding-auction-servers/blob/68c22a0c61d8320b655328dcfe0b28c59fd69475/production/packaging/aws/common/ami/otel_collector_config.yaml) as the collector config is part of the AMI and therefore attestation.

**Comment by pmeric** [comment]
Hi Fabian, the AMI is not attested, only the EIF is attested. Therefore, the AMI can vary, though the EIF must be identical.

**Comment by xinggao01** [comment]
> It looks like an easy way to kill ad tech traffic as you can just inject a bunch of consented traffic requests with new guids until the servers go down.
> 
> On our side we also noticed that there are many metrics with many dimensions that are created and it generates a significant cost already.

To send consented requests to B&A servers, it has to include the consented token that is only known to server owner.

Thanks for your feedback. Can you share more details on metrics and dimensions you think are generating unnecessary cost? We will do some investigation.

**Comment by maciejkowalczyk** [comment]
Setting `generation_id=consented` might possibly be a one way of fixing the issue of services not "forgetting" about consented requests processed long time ago.

In a minimal test B&A seller+buyer cluster that had already processed five consented requests I've applied following workaround:
```
processors:
  filter/generation_id:
    error_mode: ignore
    metrics:
      datapoint:
        - attributes["generation_id"] != nil and attributes["generation_id"] != "not_consented"
```
and observed that `monitoring.googleapis.com/billing/bytes_ingested` metric has dropped by ~250B/s and `250/5*3600*24*30*0.2580/1e6` is ~30
